---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=257.3
  sha1: e4442afcc64123e11f2b33cc2be799a0b59207d0
- name: bosh-photon-cpi
#  url: file:///CPI_RELEASE
#  sha1: CPI_SHA1
  url: https://s3.amazonaws.com/concourse-photon/bosh-photon-cpi-1.0.0.tgz
  sha1: 71626961a8505447fa34ca569f97f8c70a0ef39a
resource_pools:
- name: vms
  network: default
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3262.7
    sha1: a6e3a39d7694557a5cae0b8f35af619edbc0ca22
  cloud_properties:
    vm_flavor: core-200
    disk_flavor: core-200
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"


disk_pools:
- name: disks
  disk_size: 20_000
  cloud_properties:
    disk_flavor: core-200

networks:
- name: default
  type: manual
  subnets:
  - range: BOSH_DEPLOYMENT_NETWORK_SUBNET
    gateway: BOSH_DEPLOYMENT_NETWORK_GW
    dns: [BOSH_DEPLOYMENT_NETWORK_DNS]
    cloud_properties:
      network_id: BOSH_DEPLOYMENT_NETWORK_ID

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: cpi, release: bosh-photon-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - {name: default, static_ips: [BOSH_DEPLOYMENT_NETWORK_IP]}

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password
      port: 4222

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    blobstore:
      address: BOSH_DEPLOYMENT_NETWORK_IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}
      options:
        endpoint: http://BOSH_DEPLOYMENT_NETWORK_IP:25250
        user: agent
        password: agent-password

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: cpi
      user_management:
        provider: local
        local:
          users:
          - {name: BOSH_DEPLOYMENT_USER, password: BOSH_DEPLOYMENT_PASSWD}
          - {name: hm, password: hm-password}

    hm:
      http: {user: hm, password: hm-password}
      director_account: {user: BOSH_DEPLOYMENT_USER, password: BOSH_DEPLOYMENT_PASSWD}
      resurrector_enabled: true

    photon: &photon
      target: http://PHOTON_CTRL_IP:9000
    #  user: PHOTON_USER
    #  password: PHOTON_PASSWD
      ignore_cert: PHOTON_IGNORE_CERT
      tenant: PHOTON_TENANT
      project: PHOTON_PROJ_ID

    agent: {mbus: "nats://nats:nats-password@BOSH_DEPLOYMENT_NETWORK_IP:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: cpi, release: bosh-photon-cpi}
  mbus: "https://mbus:mbus-password@BOSH_DEPLOYMENT_NETWORK_IP:6868"

  properties:
    agent: {mbus: "https://mbus:mbus-password@0.0.0.0:6868"}
    blobstore:
      provider: local
      options:
        blobstore_path: /var/vcap/micro_bosh/data/cache
    ntp: *ntp
    photon: *photon
